export const TOGGLE_DARKMODE = 'TOGGLE_DARKMODE'
export const SET_IPV4 = 'SET_IPV4'
export const SET_IPV6 = 'SET_IPV6'
export const SET_GEO_DATA = 'SET_GEO_DATA'
export const GET_USER_DATA = 'GET_USER_DATA'
