export const TOGGLE_DARKMODE = 'TOGGLE_DARKMODE'
export const GET_IPV4 = 'GET_IPV4'
export const SET_IPV4 = 'SET_IPV4'
export const GET_IPV6 = 'GET_IPV6'
export const SET_IPV6 = 'SET_IPV6'
export const GET_GEODATA = 'GET_GEODATA'
export const SET_GEODATA = 'SET_GEODATA'
